### ISSUE TITLE
Works on single post pages?

### ISSUE THREAD

**Issue by pcmhatre** [jimmitchell/micro-masonry#1]
Does this work on photos posted in a single post?

**Comment by jimmitchell** [comment]
It could, but you'd have to type out the html for an unordered list yourself. Here's a framework of what it'd look like:

```
<ul class="grid">
    <li class="grid-item"><img src="example1.jpg" /></li>
    <li class="grid-item"><img src="example2.jpg" /></li>
    <li class="grid-item"><img src="example3.jpg" /></li>
</ul>
```

I did test it out and it worked pretty well.
